### DISCUSSION TITLE
Equipment Parameters Beta - discussion

### DISCUSSION THREAD

**Discussion by PeteRager** [PeteRager/lennoxs30#197] [General]
Let use this discussion for questions, issues and discoveries for this beta

**Comment by PeteRager** [comment]
Current docs:

https://github.com/PeteRager/lennoxs30/blob/master/docs/parameters.md

**Comment by PeteRager** [comment]
It seems that when I set this number.ragehouse_par_iu_continuous_indoor_blower_airflow and then immediately press the parameter update button, it immediately takes affect without running a system test.  This could be because the Fan is not currently on.  Will retest with the fan on.

**Comment by subtlybeast** [comment]
Quick smoke test:
1- The per-zone CFM demand paramteres (circulation/cooling/heating) were created as numerical parameters under the S30.
2- Switching off safety from Lovelace + adjusting the cooling CFM parameter worked exactly as expected: the parameter was updated mid-cooling cycle without interruptions.
AWESOME!

Once I get some time I will run some more testing scenarios, check how the automation is handling it etc and will report back.

**Reply by PeteRager** [reply]
That sounds very promising.  

One anomaly I’m seeing is some diagnostic data is dropping out after I make a parameter adjustment and use the parameter update button, switching the diagLevel back to zero then to 2 - seems to resolve it.  Specifically the indoor blower rpm and indoor power, and 24vac voltage. 

I need to do some more testing to see if it happens all the time.

**Reply by subtlybeast** [reply]
Interesting behaviour:
- When I change the Zone Cooling CFM value from the interface, it works perfectly fine (CFM changes without interruption to the cycle nor the system going into testing more).
- When I try to do the same using the service call, the system goes into the reported test cycle - it is worth noting that in the Developer tools > Services > UI mode I was unable to select the target entity for the service, but was able to add it using YAML to update the value, but puts the system in test mode - here is the code I am using. 
_config_hvac_ac_upper_targetairflow_ is a helper I created to maintain the target (Calculated) value I want the CFM to be.

`service: lennoxs30.set_zonetest_parameter
data_template:
  entity_id: number.system_par_zone_2_cooling_cfm
  enabled: false
  value: >-
    {{((states.input_number.config_hvac_ac_upper_targetairflow.state |float
    /5)|int )*5}}`

**Reply by PeteRager** [reply]
To get the same behavior as the UI call the number set_value method on the parameter.  

The zone test should mimic what happens when you are in that zone screen at hit the start button.  At some point try that from the panel and see what happens.  It may turn out that the zone test method isn’t very useful. It also may be that enabled should be true - that’s what gets sent when the start button is pressed.  Enabled false gets set when the test stops - so seeing the Lennox system go into a test cycle when exiting the test may be the way that works.

**Reply by subtlybeast** [reply]
Working as expected - using automation I turn off Safety, then adjust the CFM then turn safety back on again (extra careful).
I am getting the same behaviour as from the panel - now trying with more tweaks to the calculations, triggers and update frequency.

**Reply by PeteRager** [reply]
How is the updated algorithm working for you?  Has improved the overall HVAC system?

**Reply by subtlybeast** [reply]
So far so good, I have not had time to tweak further but it is indeed improving the overall system (start with a high CFM if there is a large gap between the current temp and the target temp, and reducing the CFM demand as the current temp approaches the target).
The System still has that bug where it pumps the AC to 100%, gets stuck, Discharge Air Temp drops to either the lower limit or coil freeze, and it keeps cycling like that till a power reset, after which it operates normally.
I failed to find the pattern that triggers this bug, but I have been pulled by life and have not put enough time into this yet.

**Reply by PeteRager** [reply]
Sounds like some progress!  I'm looking at a different use case, but it's actually pretty similar to what you've done.

Current State: I have wood stove in my living room; that is fairly close to the large air intake on the first floor.  When the wood stove heats up, I automate turning the HVAC fan on to move the air around to other rooms.  (This was actually the whole reason I wrote this integration - homekit wouldn't allow me to turn the fan on / off!)

Next Step:  Dynamically adjust the fan CFM, based on the difference in temp between the living room and the other rooms.  Which I think is what you did for cooling?

**Reply by subtlybeast** [reply]
It is very similar, yes!
What I did is that I created 4 helpers (my setup parameters) to serve as like 2 points on a line graph with Temp Gap as the X axis and CFM as the Y axis.
- Max temp Gap
- Min Temp Gap
- Max airflow
- Min Airflow

I created 2 automations, the first calculates the "Target Airflow (another helper)" basically by
 (((Current Temp Gap between Actual and Target / (Max Temp Gap - Min Temp Gap)) * (Max airflow - Min Airlflow)) + Min airflow.

The second takes the Target Airflow, rounds it to the nearest 5CFM and sets the equipment.

In the first automation, I eventually want to account for outside temperature and to make an exception if the AC is stuck at 100% to boost up the CFM to prevent coil freeze, I cannot get the time to do that yet.

**Reply by nlbgt** [reply]
@subtlybeast I’ve been working to do something very similar and just came across the same issue of the AC getting stuck at 100%. Did you ever come across what causes this?

**Reply by subtlybeast** [reply]
It has been driving me nuts and still is.

No one was able to solve that random stuck at 100% AC, A lennox eng came at some point and gaslighted the whole thing.
What I do is that once I detect that the cooling is at 100%, I update the CFM demand to increase the blower speed so that the coil does not freeze. 50% of the times the AC re-adjusts after a few 100% runs, other times I end up restarting the system (power off, power on - the soft restart does not solve the problem).

If you ever find the fix, let us know.

**Reply by nlbgt** [reply]
No fix, but so far my unit seems to sort itself out by using the `System_reset_smarthub` (button.system_reset_smarthub) entity. I was doing the power down, power up for a while. A shame this happens with the Lennox system, if it wasn't for this issue, I'd almost have a ZONED variable system running... Appreciate the discussion.

**Comment by PeteRager** [comment]
There is a Lennox issue with diagnostic data when the iu continuous blower CFM is set from either the panel or the integration.   Current solution is to set diagLevel to 0 and back to 2

https://github.com/PeteRager/lennoxs30/issues/201

**Comment by PeteRager** [comment]
Finally got some time to work on setting the Circulation Fan CFM on my Single Zone Lennox Variable Speed system.

Here's a script that does the necessaries.

```
lennoxs30_set_fan_cfm:
  description: "Set the CFM for the Fan"
  fields:
    system_name:
      description: "system name for the LennoxS30"
      example: "system"
    cfm:
      description: "CFM to set the parameter to"
      example: "250"
  mode: queued
  sequence:
    - service: system_log.write
      data:
        level: info
        message: "Seting Fan CFM to {{cfm}}"
        logger: lennoxs30
    - service: switch.turn_off
      target:
        entity_id: "switch.{{system_name}}_parameter_safety"
    - service: number.set_value
      target:
        entity_id: "number.{{system_name}}_par_iu_continuous_indoor_blower_airflow"
      data:
        value: "{{cfm}}"
    - delay: "00:00:05"
    - service: button.press
      target:
        entity_id: "button.{{system_name}}_parameter_update"
    - service: switch.turn_on
      target:
        entity_id: "switch.{{system_name}}_parameter_safety"
    - service: system_log.write
      data:
        level: info
        message: "Waiting 1:30 for S30 to update"
        logger: lennoxs30
    - delay: "00:01:30"
    - service: number.set_value
      target:
        entity_id: "number.{{system_name}}_diagnostic_level"
      data:
        value: "0"
    - delay: "00:00:01"
    - service: number.set_value
      target:
        entity_id: "number.{{system_name}}_diagnostic_level"
      data:
        value: "2"
    - service: system_log.write
      data:
        level: info
        message: "Set CFM Complete"
        logger: lennoxs30

```
