### DISCUSSION TITLE
Is it possible to make a button card that toggles the FAN_MODE from ON/OFF?

### DISCUSSION THREAD

**Discussion by Aeongen** [PeteRager/lennoxs30#231] [Q&A]
Curious if that is possible and if so how. This feature would go great with automating it with an air quality sensor.

**Comment by PeteRager** [comment]
I would think it is possible.   The fan control has three states On, Auto and Circulate.  What I do to automate it is use the service calls. 

```
    - service: climate.set_fan_mode
      target:
        entity_id: climate.air_conditioner
      data:
        fan_mode: "on"
```

So I would think you could create an automation that turns the fan on based on hitting some threshold on the air quality monitor and then turn it off when the air quality improves or just run it for an hour.

You may also be able to control the speed if you have a variable speed fan.  There's a sample script here
https://github.com/PeteRager/lennoxs30/tree/master/samples/set_fan_cfm

Does that help?

**Comment by Aeongen** [comment]
Thank you so much! That worked!

Do you know if there's an easy way for the button card to reflect the actual state of the fan mode? Such as Auto or On? Right now show_state shows off regardless of the fan mode.
![11](https://user-images.githubusercontent.com/131268275/233698049-9d03e440-b6a5-4880-b82b-df293de41a9f.JPG)

**Comment by PeteRager** [comment]
I use a binary sensor template to determine if the fan is on.  

You may be able to use this sensor as the entity is the button card?

```
binary_sensor:
  - platform: template
    sensors:
      air_conditioner_fan:
        value_template: >-
          {{ state_attr('climate.air_conditioner','fan') == 'on' }}
````
