### DISCUSSION TITLE
How to detect if the blower fan is on or off

### DISCUSSION THREAD

**Discussion by amstoneberger** [PeteRager/lennoxs30#278] [Q&A]
Hi, I am trying to set up an automation that takes action when the blower fan turns on or off. It doesn't appear that any entities report this information by default. I have tried using a state change for the thermostat "current action" attribute from idle to fan, but it isn't triggering when the blower turns on. I see other options in this attribute for heating and cooling, and I'm thinking the fan state wouldn't be active if the system is heating as well.

Ideally I'd like to just use the blower fan status no matter if the system is set to cool, heat, cool/heat or actively cooling or heating. We also keep the circulate option turned on in the thermostat, so the trigger should go if the blower fan is on for circulation. I have included a screenshot of how the trigger is currently configured. Would it be possible to add this to the integration? I've seen suggestions on other forums to use a power meter outlet on the blower fan unit, but I'd like to do this without additional hardware if possible. Any help would be appreciated, thanks!

System is Lennox E30

![image](https://github.com/PeteRager/lennoxs30/assets/47669098/a6a43c83-ec64-43c7-b60b-ee7cbdac88dc)

EDIT:
Some additional info: when the blower turns on due to the circulate mode triggering, the status in HA doesn't change from "idle", this may be a bug and why I can't get my automation to work. Reading through the docs, it seems like the status should change from idle to one of either fan, cooling, or heating. I do get the state change if it goes to heating or cooling. The fan blower was turned on for circulation in the screenshot below, status still displays idle.

![image](https://github.com/PeteRager/lennoxs30/assets/47669098/593d7feb-e448-40d3-b6e9-905aef6907b2)

**Comment by PeteRager** [comment]
There is an attribute of the climate entity called "fan" that indicates if the fan is running - this will be true when the fan is running.  Note: this attribute will not be true if the hvac is currently heating or cooling,   

https://github.com/PeteRager/lennoxs30#supported-data

**Comment by PeteRager** [comment]
Here is a template I use to determine if the system is running and to bring the fan attribute into its own sensor so I can record it and use it in graphs.  Note, my system is AC only so there are other modes you may want to add to the expression. 

```
binary_sensor:
  - platform: template
    sensors:
      air_conditioner_fan:
        value_template: >-
          {{ state_attr('climate.air_conditioner','fan') == 'on' }}
      air_conditioner_running:
        value_template: >-
          {{ state_attr('climate.air_conditioner','hvac_action') == 'cooling' or state_attr('climate.air_conditioner','hvac_action') == 'drying' or state_attr('climate.air_conditioner','fan') == 'on'  or state_attr('climate.air_conditioner','fan_mode') != 'auto' }}

```
