### DISCUSSION TITLE
S40 Thermostat can't find fan modes in automations

### DISCUSSION THREAD

**Discussion by stealth-71** [PeteRager/lennoxs30#293] [General]
I recently got an S40 and I have setup the integration.  I can see and set HVAC and Fan modes through the UI card, but I only see the HVAC modes in my automations.  I want to turn the fan to on when I have a trigger.  I am having a hard time finding this.  Is it supported for an S40?

**Comment by PeteRager** [comment]
Yes, you can do that.  Here's an example service call.

```
    - service: climate.set_fan_mode
      target:
        entity_id: climate.air_conditioner
      data:
        fan_mode: "on"
```
