### DISCUSSION TITLE
Simple way to determine if the system is on or off and cooling or heating.

### DISCUSSION THREAD

**Discussion by maccampb** [PeteRager/lennoxs30#294] [Q&A]
Hi all,

Just installed the HA integration for my S30 thermostat and that to @PeteRager  for a great job... 

Very smooth and seamless....

Lots and lots of data and information... Which leads me to my question... Are the any binary entities that can indicate state of the system (on, off, heating, cooling)? I'm trying to build correlations with my indoor air quality and the furnace on/off cycles, so looking for on off type data first.

I've looked at the 67 entities that are currently show and not having much luck...

Any suggestions appreciated...

MAC

**Comment by PeteRager** [comment]
I'd start with looking at the hvac_action of the climate entities.  Typically that attribute is brought into an entity by using a template.

```
sensor:
  - platform: template
    sensors:
      bedroom_hvac_action:
        value_template: >-
          {{ state_attr('climate.bedroom_thermostat','hvac_action') }}
```

This makes it easy to graph what each zone is doing.  From there create whatever binary_sensor you want.

There also may be diagnostic data that has more detailed info on exactly what the furnace or heat pump is doing.
