### DISCUSSION TITLE
Can't use preset_mode on E30?

### DISCUSSION THREAD

**Discussion by jenfil82** [PeteRager/lennoxs30#327] [Q&A] [answered]
Hello,

I got issues calling the service to set the thermostat to away, here is the service I'm trying to call:

service: climate.set_preset_mode
target: {entity_id: ba2a3b596c48f5aefe065e419a59cc4c}
data: {preset_mode: away}

And I get this as answer: 
Failed to call service climate.set_preset_mode. Entity climate.icomfort_e30_01fd13_thermostat does not support this service.

I am trying to put this in an automation that sets the thermostat to away when I leave the house, like this:
device_id: d08b8c0c51496aff3f4abfc613437510
domain: climate
entity_id: ba2a3b596c48f5aefe065e419a59cc4c
type: set_preset_mode
preset_mode: away

Any idea what I'm doing wrong?

**Comment by PeteRager** [comment]
Please look at the example of how to set the preset mode in the home assistant documentation. 

https://www.home-assistant.io/integrations/climate/

Use the entity id, instead of device ids.

If that doesn't work take a look at the climate entity in developer tools / states. There is an attribute called zoneEnabled if that is false that would prevent that service call from being available.  Post a screen shot of those attributes.

**Comment by jenfil82** [comment]
Thanks Pete, appreciate the quick reply! In the test service call, I did try it on the entity directly. I've checked attributes, and I am missing the zoneenabled one :(
<img width="508" alt="Screenshot 2024-06-10 at 8 45 34 AM" src="https://github.com/PeteRager/lennoxs30/assets/166951034/d46628b5-34d2-4245-a3d8-c08b41f7fcfa">

**Comment by PeteRager** [comment]
Please provide a complete list of the attributes and values.  Best way is to copy the text and the paste as a code block. Use the slash icon on the leftmost of the GitHub text editor to insert a code block.  

Do the same with your automation YAML and the complete error reported in the home-assistant.log file.  

Finally, in the integration panel download and attach the diagnostics.

**Comment by jenfil82** [comment]
Here are the attributes and values:

```
hvac_modes:
  - "off"
  - heat
  - cool
  - heat_cool
min_temp: 15.5
max_temp: 37
current_temperature: 23
temperature: 25
target_temp_high: null
target_temp_low: null
current_humidity: 46
hvac_action: idle
friendly_name: iComfort E30 01fd13 Thermostat
supported_features: 387
```

Here is my automation YAML:
```
alias: AC off when leaving home
description: ""
trigger:
  - platform: state
    entity_id: device_tracker.karen_s22
    to: not_home
  - platform: state
    entity_id: device_tracker.zflip5
    to: not_home
condition:
  - condition: state
    entity_id: device_tracker.karen_s22
    state: not_home
  - condition: state
    entity_id: device_tracker.zflip5
    state: not_home
action:
  - service: climate.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
        - climate.guest
        - climate.bedroom
        - climate.office
    enabled: false
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      floor_id:
        - basement
        - groundfloor
        - outside
        - upstairs
    enabled: false
  - service: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
        - media_player.shield_2
        - media_player.xbr_75x850d_2
        - media_player.home_theater
    enabled: false
  - service: climate.set_preset_mode
    target:
      entity_id: climate.icomfort_e30_01fd13_thermostat
    data:
      preset_mode: away
mode: single
```
The error log:

> 
> Executed: June 10, 2024 at 14:05:53
> Error: Entity climate.icomfort_e30_01fd13_thermostat does not support this service.
> Result:
> 
> params:
>   domain: climate
>   service: set_preset_mode
>   service_data:
>     preset_mode: away
>     entity_id:
>       - climate.icomfort_e30_01fd13_thermostat
>   target:
>     entity_id:
>       - climate.icomfort_e30_01fd13_thermostat
> running_script: false
> 

The lines from home-assistant.log:

> 2024-06-10 14:05:53.636 ERROR (MainThread) [homeassistant.components.automation.ac_off_when_leaving_home] AC off when leaving home: Error executing script. Error for call_service at pos 4: Entity climate.icomfort_e30_01fd13_thermostat does not support this service.
> 2024-06-10 14:05:53.637 ERROR (MainThread) [homeassistant.components.automation.ac_off_when_leaving_home] Error while executing automation automation.ac_off_when_leaving_home: Entity climate.icomfort_e30_01fd13_thermostat does not support this service.

And finally, the diagnostic log:
[homekit_controller-e5a839b19b3a0e9ed12fd16c936be64b-iComfort E30 01fd13-d08b8c0c51496aff3f4abfc613437510.json](https://github.com/user-attachments/files/15777538/homekit_controller-e5a839b19b3a0e9ed12fd16c936be64b-iComfort.E30.01fd13-d08b8c0c51496aff3f4abfc613437510.json)
