### ISSUE TITLE
How can I use select one of the Fan Modes in an Automation

### ISSUE THREAD

**Issue by klkohl** [PeteRager/lennoxs30#251]
I'm trying to create an Automation that sets the Fan Mode, but I'm not seeing that as an option. Is there a way to do this?

![image](https://github.com/PeteRager/lennoxs30/assets/88909821/df3c3dcb-923f-40d3-950e-f146f5004f04)

**Comment by PeteRager** [comment]
This is what the YAML looks like. Valid modes are on, circulate, auto

```
  action:
    - service: climate.set_fan_mode
      target:
        entity_id: climate.air_conditioner
      data:
        fan_mode: "on"
```

`
![IMG_3050](https://github.com/PeteRager/lennoxs30/assets/76050312/435aa9f9-8f41-44ed-a8b0-b82c610f051e)
